### Create Article
POST http://localhost:8080/post
Content-Type: application/json

{
    "title": "create post test",
    "content": "content"
}

### Modify Article
PUT http://localhost:8080/post/1248
Content-Type: application/json

{
    "title": "modify post test",
    "content": "modified content"
}

### Delete Article
DELETE http://localhost:8080/post/1248
Content-Type: application/json
